### ISSUE TITLE
脱敏列名是否有用

### ISSUE THREAD

**Issue by searchlink** [RyanWangZf/transtab#5]
一些真实应用场景，特征列名是脱敏，也就是没有任何含义的，这个时候特征名还能否进行embedding？

**Comment by RyanWangZf** [comment]
If the column names are absolute nonsense, I do not think their "semantics" can transfer across the table. Like how do we tell the similarity between `0f1cb7e42aed2a4e67d25d389b2103f6` and `d7d8da2281427cb541d6d9859d41ae60`? Even they are generated based on words `transtab` and `TransTab` through MD5 hash generator, respectively.

Nonetheless, if the columns are in advance tokenized by a private tokenizer, then it is promising they can be transferred. In this case, two words `transtab` and `TransTab` will still share similar token ids.

Hope this answer helps you.
