### ISSUE TITLE
Mistake in TransTabForCL implementation?

### ISSUE THREAD

**Issue by somaonishi** [RyanWangZf/transtab#7]
Hi,  I was looking at your code and found what I believe to be an implementation error.
I think you forgot to append the cls token.

https://github.com/RyanWangZf/transtab/blob/5923c6b29bb4d0917958b2d9dbd0f232c226c1f1/transtab/modeling_transtab.py#L1140-L1145

**Comment by RyanWangZf** [comment]
Hi, thanks for your pointing it out. I think you are right. I need to add CLS token before `feat_x` going to `self.encoder`.
