### ISSUE TITLE
[issue] model.update()

### ISSUE THREAD

**Issue by BingzhaoZhu** [RyanWangZf/transtab#8]
https://github.com/RyanWangZf/transtab/blob/4e7df4ae1a4f95614e230934d3125d5a6746aeb8/transtab/modeling_transtab.py#L835

When updating `num_class` the loss function should also be updated. Now this causes an error when we switch from `num_class=2` to `num_class>2`, since they use different losses. See the code below

  https://github.com/RyanWangZf/transtab/blob/4e7df4ae1a4f95614e230934d3125d5a6746aeb8/transtab/modeling_transtab.py#L944

**Comment by RyanWangZf** [comment]
Hi, thanks for your interest in our work! We have checked and fixed this problem with a new comment. Please check and have fun! Let me know if there is any other problem.
